frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Scope;
use Yii;
use frontend\models\RequestForm;
use yii\base\InvalidParamException;
use yii\web\NotFoundHttpException;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $layout = 'index';
    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex($id = null)
    {
        if ($id) {
            $model = Scope::find()->active()->where('id=:id', ['id' => $id])->one();

            if (!$model) {
                throw new NotFoundHttpException();
            }
        } else {
            $model = Scope::find()->sorted()->one();
        }

        return $this->render('index', [
            'model' => $model
        ]);
    }

    public function actionForm()
    {
        $this->layout = 'inner';

        $model = new RequestForm();
        return $this->render('form', [
            'model' => $model,
        ]);
    }

    public function actionFormSubmit()
    {
        Yii::$app->response->format = 'json';

        $model = new RequestForm();

        $result = [
            'success' => true
        ];
        if (!$model->load(Yii::$app->request->post()) || !$model->validate() || !$model->sendEmail()) {
            $result = [
                'success' => false,
                'errors' => array_keys($model->errors)
            ];
        }

        return $result;
    }

    public function actionFormComplete()
    {
        $this->layout = 'inner';
        return $this->render('complete');
    }
}

frontend/views/layouts/_footer.php
<?php
/* @var $this \yii\web\View */
?>
<div id="footer">
    <div class="wrap">
        <a class="copyright" href="http://radigital.ru/" target="_blank">Собрано в RA Digital</a>
        <div class="social" data-url="<?=Yii::$app->request->hostInfo?>" data-img="<?=Yii::$app->request->hostInfo?>/images/logo.jpg" data-title="Это заголовок" data-desc="Это надпись поменьше">
            <a href="#" class="vk" title="Вконтакте"></a><a href="#" class="fb" title="Facebook"></a>
        </div>
    </div>
</div>

frontend/views/layouts/_head.php
<?php
/* @var $this \yii\web\View */
use frontend\widgets\MenuWidget;
use yii\helpers\Url;

?>
<div id="head">
    <div class="wrap">
        <a class="logo" href="/"><img src="/images/logo.jpg" alt="Дикий филин"/></a>
        <a class="send-button" href="/<?= Url::to('site/form') ?>/">Поставь свою метку</a>
        <?= MenuWidget::widget() ?>
    </div>
</div>

frontend/views/layouts/index.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */
?>
<?php $this->beginContent('@app/views/layouts/main.php'); ?>
<div class="index-page">
    <?= $this->render('_head') ?>
    <div id="content">
        <?= $content ?>
    </div>
    <?= $this->render('_footer') ?>
</div>
<?php $this->endContent(); ?>

frontend/views/layouts/inner.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */
?>
<?php $this->beginContent('@app/views/layouts/main.php'); ?>
<div class="inner-page">
    <?= $this->render('_head') ?>
    <div id="content">
        <?= $content ?>
    </div>
    <?= $this->render('_footer') ?>
</div>
<?php $this->endContent(); ?>

frontend/views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="shortcut icon" type="image/png" href="/favicon.png"/>
    <link rel="stylesheet" href="/assets/css/styles.min.css"/>
</head>
<body>
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
<script src="/assets/js/scripts.js"></script>
</body>
</html>
<?php $this->endPage() ?>