common/models/Scope.php
<?php

namespace common\models;

use common\components\SaveImageBehavior;
use Yii;
use yii\db\ActiveRecord;
use yii\helpers\Url;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the model class for table "scopes".
 *
 * @property integer $id
 * @property string $title
 * @property string $image
 * @property string $active
 */
class Scope extends ActiveRecord
{
    /**
     * @inheritdoc
     * @return ScopeQuery
     */
    public static function find()
    {
        return new ScopeQuery(get_called_class());
    }

    public function behaviors()
    {
        return [
            'sort' => [
                'class' => SortableGridBehavior::className(),
                'sortableAttribute' => 'order'
            ],
            'image' => [
                'class' => SaveImageBehavior::className(),
                'attributeName' => 'image',
                'savePath' => '@upload',
                'generateNewName' => true,
                'protectOldValue' => true,
                'resize' => '1920x1600'
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'scopes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'active'], 'required'],
            [['title'], 'string', 'max' => 255],
            [['image'], 'file',
                'extensions' => 'jpg, jpeg, png',
                'mimeTypes' => 'image/jpeg, image/png',
                'maxSize' => 1024*1024*20
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'title' => 'Название',
            'image' => 'Изображение',
            'active' => 'Активна',
        ];
    }

    public function getImageUrl()
    {
        return '/upload/' . $this->image;
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\User;
use common\models\UserEditForm;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'user'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionUser()
    {
        $model = new UserEditForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->update()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
        return $this->render('user', [
            'model' => $model,
        ]);
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Scope;
use Yii;
use frontend\models\RequestForm;
use yii\base\InvalidParamException;
use yii\web\NotFoundHttpException;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $layout = 'index';
    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex($id = null)
    {
        if ($id) {
            $model = Scope::find()->active()->where('id=:id', ['id' => $id])->one();

            if (!$model) {
                throw new NotFoundHttpException();
            }
        } else {
            $model = Scope::find()->sorted()->one();
        }

        return $this->render('index', [
            'model' => $model
        ]);
    }

    public function actionForm()
    {
        $this->layout = 'inner';

        $model = new RequestForm();
        return $this->render('form', [
            'model' => $model,
        ]);
    }

    public function actionFormSubmit()
    {
        Yii::$app->response->format = 'json';

        $model = new RequestForm();

        $result = [
            'success' => true
        ];
        if (!$model->load(Yii::$app->request->post()) || !$model->validate() || !$model->sendEmail()) {
            $result = [
                'success' => false,
                'errors' => array_keys($model->errors)
            ];
        }

        return $result;
    }

    public function actionFormComplete()
    {
        $this->layout = 'inner';
        return $this->render('complete');
    }
}

frontend/views/site/complete.php
<?php
/* @var $this yii\web\View */
$this->title = 'Ваша заявка успешно отправлена';
?>
<div id="complete">
    <div class="message">Отлично! Скоро ваша компания окажется на карте!</div>
    <div class="social" data-url="<?=Yii::$app->request->hostInfo?>" data-img="<?=Yii::$app->request->hostInfo?>/images/logo.jpg" data-title="Это заголовок" data-desc="Это надпись поменьше">
        <div class="text">Рассказажите об этом своим друзьям.</div>
        <a href="#" class="vk" title="Вконтакте"></a><a href="#" class="fb" title="Facebook"></a>
    </div>
</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/form.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\RequestForm */

$this->title = 'Поставь свою метку';
?>
<form id="form" method="POST" action="/<?= Url::to('site/form') ?>/">
    <div class="message">Заполните форму и отправьте, чтобы мы поставили метку</div>
    <div class="field">
        <?= Html::activeTextInput($model, 'company', ['placeholder' => $model->getAttributeLabel('company')]) ?>
    </div>
    <div class="field">
        <?= Html::activeTextInput($model, 'work', ['placeholder' => $model->getAttributeLabel('work')]) ?>
    </div>
    <div class="field">
        <?= Html::activeTextInput($model, 'address', ['placeholder' => $model->getAttributeLabel('address')]) ?>
    </div>
    <div class="field">
        <?= Html::submitButton('Отправить') ?>
    </div>
</form>

frontend/views/site/index.php
<?php
/* @var $this yii\web\View */
/* @var $model common\models\Scope */
$this->title = !empty($model->title) ? $model->title : Yii::$app->params['siteName'];
?>
<div id="map">
    <img src="<?=!empty($model->image) ? $model->imageUrl : '/images/map.png' ?>" alt=""/>
</div>